export default {
  navColorInactive: "rgba(255, 255, 255, 0.9)",
  navColorActive: "rgba(255, 255, 255, 0)",
  navTransitionDuration: ".35s",
  offWhite: "#f8f8ff",
  offBlack: "#1a1a1d;",
  white: "#f0f0f0",
  gridColChat: "2 / 3",
  gridRowChat: "2 / -1",
  layout: {
    gridColNav: "1 / -1",
    gridRowNav: "1 / 2",
    gridColChat: "2 / 3",
    gridRowChat: "2 / -1",
  },
  zIndex: {
    chat: "10",
    backdrop: "20",
    modal: "25",
  },
  backgroundColorDark: "#2b3a67;",
  backgroundColorLight: "#9aa9d5;",
  backgroundColorDarkGray: "#333",
  backgroundColorDarkerGray: "rgba(43, 43, 43, 1)",
  backgroundColorLightGray: "#c4c4c4;",

  textColorLight: "#fff;",
  textColorDark: "black",

  fontSizeS: "1rem",
  fontSizeM: "1.5rem",
  fontSizeL: "2rem",
  borderRadiusBtn: "3px",
  borderRadiusBtnL: "5px",
  borderRadius: "1rem",
  borderRadiusL: "15%",
  transitionSpeed: ".3s",
};
